name: Enchancement
description: File an Enhancement request
title: "[Feature]: "
labels: ["feature", "enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for your request.
      options:
      - label: I have searched the existing issues and confirmed this is not a duplicate.
        required: true
  - type: textarea
    id: whats-new
    attributes:
      label: Feature or Enhancement Request
      description: What would you like to see added to the project?
      placeholder: Tell us what you would like to see!
      value: "This project needs a new feature!"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/nginx/best-practices/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
